# Yashwant Desai –  Python_Advanced_Assignment_22

# Q1. What are the benefits of the built-in array package, if any?

Python does not have a built-in "array package" in the same way it has built-in data structures like lists or dictionaries. However, Python does have a module called array that provides an array data type. The array module is part of the Python Standard Library, and it's used to create and manipulate arrays of data.

The array module in python provides following benefits:

Typed Arrays: array allows you to create arrays that can only hold elements of a single data type, making it suitable for working with homogeneous data.

Efficient Memory Usage: Arrays typically use less memory compared to lists, which can be advantageous for large datasets, especially with numerical data.

Faster Access: Accessing elements in an array is generally faster than accessing elements in a list because arrays provide direct memory access to their elements.

Supported Numeric Data Types: The array module supports various numeric data types, which is useful for numerical computations.

Array Methods: The array module provides methods for common array operations, making it more efficient and convenient for certain tasks.

Below is an example.

In [1]:
from array import array

my_array = array('i', [1, 2, 3, 4, 5])

print(my_array[0])

my_array.append(6)

my_array.remove(3)

print(my_array)

1
array('i', [1, 2, 4, 5, 6])


# Q2. What are some of the array package's limitations?

The array module has the following limitations:

o Lack of versatility: Arrays can store only elements of a single data type, making them less flexible than lists.

o Limited functionality: Arrays offer a limited set of methods and operations compared to Python lists.

o Fixed size: The size of an array is fixed at creation, which can be less convenient for dynamically adding or removing elements.

o Fewer built-in features: Arrays lack some of the built-in features of lists, such as sorting, reversing, and comprehensions.

o Integer-only indexing: Arrays only support integer indexing, while lists offer more flexible indexing options.

o No mixed types: Arrays require elements to have a compatible data type, making them less suitable for mixed data types.

o Less common usage: The array module is not as widely used as lists or NumPy arrays for numerical operations.

o No built-in iteration protocol: Arrays don't directly support the Python iteration protocol, unlike lists.

# Q3. Describe the main differences between the array and numpy packages.

Below are main differences between the array and numpy packages.

o The array module provides basic support for arrays but is limited to a few numeric data types (e.g., integers and floats). It enforces that all elements must have the same data type.

o NumPy provides extensive support for a wide range of data types, including complex numbers, strings, booleans, and user-defined data types

o The array module offers a basic set of methods for array creation and manipulation

o NumPy provides a vast collection of mathematical functions and operations for array manipulation. It provides capabilities for linear algebra, statistical analysis, and more.

o The array module primarily deals with one-dimensional arrays and provides limited support for multi-dimensional arrays.

o NumPy excels in handling multi-dimensional arrays. It provides convenient ways to create, reshape, and perform operations on arrays with multiple dimensions.

o NumPy is highly optimized for numerical operations and is generally faster than the array module, particularly for complex mathematical computations.

o Arrays created with the array module support basic indexing and slicing similar to Python lists.

o NumPy provides advanced indexing and slicing techniques, making it easier to work with specific elements or subarrays within multi-dimensional arrays.

# Q4. Explain the distinctions between the empty, ones, and zeros functions.

The empty, ones, and zeros functions are used to create NumPy arrays with specific initialization values. Here are the distinctions between these functions.

o empty: Creates an uninitialized array with the specified shape, data type, and memory layout.

empty_array = np.empty((2, 3), dtype=int)

o ones: Creates an array filled with ones with the specified shape, data type, and memory layout.

ones_array = np.ones((2, 3), dtype=int)

o zero: Creates an array filled with zeros with the specified shape, data type, and memory layout.

zeros_array = np.zeros((2, 3), dtype=int)

In [2]:
import numpy as np
empty_array = np.empty((2, 3), dtype=int)

In [3]:
import numpy as np
ones_array = np.ones((2, 3), dtype=int)

In [4]:
import numpy as np
zeros_array = np.zeros((2, 3), dtype=int)

# Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

The fromfunction function, the role of the callable argument is to define how the values in the new output array are computed based on their coordinates. The callable function you provide takes the coordinates along each dimension as arguments and returns the corresponding value for that position in the array. This allows you to create arrays with custom or complex patterns based on the specific rules or calculations you define in the callable function

In [5]:
import numpy as np
def my_function(x, y):
    return x + y
shape = (3, 3)
result = np.fromfunction(my_function, shape)
print(result)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


# Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

A numpy array is combined with a single-value operand (a scalar, such as an integer or a floating-point value) through addition, as in the expression A + n, NumPy performs an element-wise addition. This means that the scalar value n is added to each element of the array A, and a new array is created with the results. The shape of the original array A and the shape of the resulting array will be the same

In [6]:
import numpy as np

A = np.array([1, 2, 3, 4])
n = 10
result = A + n
print(result)

[11 12 13 14]


# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

Combined operation-assign operators (e.g., +=, -=, *=) in NumPy can be used for array-to-scalar operations, and they modify the original array in-place. The specific operator is applied to each element of the array with the scalar operand, resulting in an updated array with the modified values. If you want to preserve the original array and create a new one with the modified values, you should use a separate assignment operation. These operators are convenient for efficiently performing in-place modifications on NumPy arrays.
Below is an example.

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr += 2 
print(arr)  
arr -= 1 
print(arr)  
arr *= 2  
print(arr)  

[3 4 5 6]
[2 3 4 5]
[ 4  6  8 10]


# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

In NumPy, you can create arrays of fixed-length strings using the numpy.string_ data type. If you attempt to allocate a longer string to one of these arrays, NumPy will automatically truncate the string to fit the specified length. If you allocate a shorter string, it may be padded with null bytes to reach the fixed length. Fixed-length string arrays are useful when you need to enforce a specific string length for your data storage.

In [8]:
import numpy as np
string_array = np.array(["apple", "banana", "cherry"], dtype=np.string_)
print(string_array)
string_array[1] = "grapefruit"
print(string_array)

[b'apple' b'banana' b'cherry']
[b'apple' b'grapef' b'cherry']


# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

When you combine two NumPy arrays using operations like addition (+) or multiplication (*), NumPy performs element-wise operations, applying the operation to corresponding elements of the arrays. The conditions for combining two NumPy arrays are:

Element-Wise Operations: Operations are performed element-wise, resulting in a new array with the same shape as the original arrays.

Shape Compatibility: The arrays being combined should have the same shape or be broadcastable to the same shape. Broadcasting is a NumPy feature that allows operations on arrays with different shapes, as long as they can be made compatible through specific rules. If the shapes are not compatible, you may encounter errors.

Below is an example.

In [9]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_addition = array1 + array2  

array3 = np.array([1, 2, 3])
array4 = np.array([2, 3, 4])
result_multiplication = array3 * array4  

print(result_addition)        
print(result_multiplication) 

[5 7 9]
[ 2  6 12]


# Q10. What is the best way to use a Boolean array to mask another array?

The best way to use a Boolean array to mask (filter) another array in Python, particularly using NumPy, is to apply the Boolean array as a mask to the target array using boolean indexing. This involves selecting elements from the target array where the Boolean mask is True and ignoring elements where it is False. It's a powerful technique for data filtering and conditional selection in NumPy.

Below is an example.

In [10]:
import numpy as np
boolean_mask = np.array([True, False, True, False, True])
data_array = np.array([1, 2, 3, 4, 5])
result = data_array[boolean_mask]
print(result)

[1 3 5]


# Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

Here are three different ways to calculate the standard deviation of a wide collection of data sorted by execution speed:

o NumPy Package (Fastest): Use the numpy.std function from NumPy for highly efficient and fast standard deviation calculations, particularly suitable for numerical data.

o Statistics Package (Moderate Speed): Utilize the statistics.stdev function from the built-in statistics module, which is moderately fast and suitable for standard Python data types like lists.

o Pure Python (Slowest): Calculate the standard deviation from scratch using pure Python, which is the slowest and least efficient option, especially for large datasets.

The choice of method depends on your specific requirements, with NumPy being the preferred choice for numerical and scientific computing due to its speed and efficiency.

In [11]:
import numpy as np

data = [1.2, 2.4, 3.3, 4.1, 5.6, 6.2]
std_dev = np.std(data)

In [12]:
import statistics

data = [1.2, 2.4, 3.3, 4.1, 5.6, 6.2]
std_dev = statistics.stdev(data)

In [13]:
data = [1.2, 2.4, 3.3, 4.1, 5.6, 6.2]
n = len(data)
mean = sum(data) / n
squared_diff = [(x - mean) ** 2 for x in data]
std_dev = (sum(squared_diff) / n) ** 0.5

# 12. What is the dimensionality of a Boolean mask-generated array?

The dimensionality of a Boolean mask-generated array in Python depends on the dimensionality of both the mask and the original array. The result of applying a Boolean mask is an array that retains the same dimensionality as the original array, with elements selected based on the mask. If the mask is 1D and filters a 1D array, the result is 1D. If the mask is 1D and filters a multi-dimensional array, the result is 1D, reducing dimensionality. If both the mask and the original array are multi-dimensional, the result maintains the same structure as the original array but with elements selected according to the mask.

Below are examples.

In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
result = arr[mask] 

In [15]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
mask = np.array([True, False, True])
result = arr[mask] 

In [16]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
mask = np.array([[True, False], [True, False], [True, True]])
result = arr[mask] 

# Done all 12 questions 

# Regards,Yashwant